services:
  app:
    image: docuseal/docuseal:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:8050:3000
    restart: always
    volumes:
      - ./docuseal:/data/docuseal
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
